### ISSUE TITLE
no module name bin.glist

### ISSUE THREAD

**Issue by kakamband** [5H4D0W-C0D3R/epic_games_store_bot#1]
after add both buildpacks & deployed to heroku & run in bash consule command "python trigger.py" get error below:

File trigger.py line 1 in module
from bin.glist import Glist
import error : no module name bin.glist

please fix it & if its possible make deploy to heroku button for easy deploy & write some help info in readme.md

waiting for your response
finest regards

**Comment by 5H4D0W-C0D3R** [comment]
> after add both buildpacks & deployed to heroku & run in bash consule command "python trigger.py" get error below:
> 
> File trigger.py line 1 in module
> from bin.glist import Glist
> import error : no module name bin.glist
> 
> please fix it & if its possible make deploy to heroku button for easy deploy & write some help info in readme.md
> 
> waiting for your response
> finest regards

added some help infos and I think the bug is gone. Let me know if need anything more.
